### ISSUE TITLE
Cloudfire server down

### ISSUE THREAD

**Issue by MarcosRodrigoT** [lautenberger/elmfire#68]
I was able to run tutorials 1 and 2, but I ran into a problem when executing tutorial 3:

```html
(venv) mrt@minerva elmfire/tutorials/03-real-fuels $ ./01-run.sh

Using LANDFIRE 2.3.0
Valid inputs received - calling CloudFire fuel weather ignition microservice
Traceback (most recent call last):
  File "/home/mrt/Projects/elmfire/cloudfire/fuel_wx_ign.py", line 350, in <module>
    run()
  File "/home/mrt/Projects/elmfire/cloudfire/fuel_wx_ign.py", line 301, in run
    response = stub.GetDomainData(fuel_wx_ign_pb2.Request( name = name ,
  File "/home/mrt/Projects/elmfire/venv/lib/python3.10/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/mrt/Projects/elmfire/venv/lib/python3.10/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.92.17.198:50052: Failed to connect to remote host: connect: Connection refused (111)"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:172.92.17.198:50052: Failed to connect to remote host: connect: Connection refused (111)", grpc_status:14, created_time:"2024-12-12T15:59:46.423415238+01:00"}"
>
tar: ./fuel/tutorial03.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
ERROR 4: ./inputs/fbfm40.tif: No such file or directory
gdalinfo failed - unable to open './inputs/fbfm40.tif'.
ERROR 4: ./inputs/fbfm40.tif: No such file or directory
gdalinfo failed - unable to open './inputs/fbfm40.tif'.
ERROR 4: ./inputs/fbfm40.tif: No such file or directory
gdalinfo failed - unable to open './inputs/fbfm40.tif'.
ERROR 4: ./inputs/fbfm40.tif: No such file or directory
gdalinfo failed - unable to open './inputs/fbfm40.tif'.
(standard_in) 1: syntax error
(standard_in) 1: syntax error
ERROR 1: ERROR - failed to load SRS definition from ./inputs/fbfm40.tif
ERROR 4: ./inputs/fbfm40.tif: No such file or directory
gdalinfo failed - unable to open './inputs/fbfm40.tif'.
ERROR 4: ./inputs/adj.tif: No such file or directory
could not open file "./scratch/dummy.tif"
ERROR 4: ./scratch/ws_0.tif: No such file or directory
ERROR 4: ./scratch/ws_1.tif: No such file or directory
ERROR 4: ./scratch/ws_2.tif: No such file or directory
ERROR 4: ./scratch/ws_3.tif: No such file or directory
ERROR 4: ./scratch/ws_4.tif: No such file or directory
ERROR 4: ./scratch/ws_5.tif: No such file or directory
ERROR 4: ./scratch/ws_6.tif: No such file or directory
ERROR 4: ./scratch/ws_7.tif: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/gdal_merge.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_merge.py", line 428, in main
    ulx = file_infos[0].ulx
IndexError: list index out of range
ERROR 4: ./scratch/wd_0.tif: No such file or directory
ERROR 4: ./scratch/wd_1.tif: No such file or directory
ERROR 4: ./scratch/wd_2.tif: No such file or directory
ERROR 4: ./scratch/wd_3.tif: No such file or directory
ERROR 4: ./scratch/wd_4.tif: No such file or directory
ERROR 4: ./scratch/wd_5.tif: No such file or directory
ERROR 4: ./scratch/wd_6.tif: No such file or directory
ERROR 4: ./scratch/wd_7.tif: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/gdal_merge.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_merge.py", line 428, in main
    ulx = file_infos[0].ulx
IndexError: list index out of range
ERROR 4: ./scratch/m1_0.tif: No such file or directory
ERROR 4: ./scratch/m1_1.tif: No such file or directory
ERROR 4: ./scratch/m1_2.tif: No such file or directory
ERROR 4: ./scratch/m1_3.tif: No such file or directory
ERROR 4: ./scratch/m1_4.tif: No such file or directory
ERROR 4: ./scratch/m1_5.tif: No such file or directory
ERROR 4: ./scratch/m1_6.tif: No such file or directory
ERROR 4: ./scratch/m1_7.tif: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/gdal_merge.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_merge.py", line 428, in main
    ulx = file_infos[0].ulx
IndexError: list index out of range
ERROR 4: ./scratch/m10_0.tif: No such file or directory
ERROR 4: ./scratch/m10_1.tif: No such file or directory
ERROR 4: ./scratch/m10_2.tif: No such file or directory
ERROR 4: ./scratch/m10_3.tif: No such file or directory
ERROR 4: ./scratch/m10_4.tif: No such file or directory
ERROR 4: ./scratch/m10_5.tif: No such file or directory
ERROR 4: ./scratch/m10_6.tif: No such file or directory
ERROR 4: ./scratch/m10_7.tif: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/gdal_merge.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_merge.py", line 428, in main
    ulx = file_infos[0].ulx
IndexError: list index out of range
ERROR 4: ./scratch/m100_0.tif: No such file or directory
ERROR 4: ./scratch/m100_1.tif: No such file or directory
ERROR 4: ./scratch/m100_2.tif: No such file or directory
ERROR 4: ./scratch/m100_3.tif: No such file or directory
ERROR 4: ./scratch/m100_4.tif: No such file or directory
ERROR 4: ./scratch/m100_5.tif: No such file or directory
ERROR 4: ./scratch/m100_6.tif: No such file or directory
ERROR 4: ./scratch/m100_7.tif: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/gdal_merge.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_merge.py", line 428, in main
    ulx = file_infos[0].ulx
IndexError: list index out of range
ERROR 4: ./scratch/lh_0.tif: No such file or directory
ERROR 4: ./scratch/lh_1.tif: No such file or directory
ERROR 4: ./scratch/lh_2.tif: No such file or directory
ERROR 4: ./scratch/lh_3.tif: No such file or directory
ERROR 4: ./scratch/lh_4.tif: No such file or directory
ERROR 4: ./scratch/lh_5.tif: No such file or directory
ERROR 4: ./scratch/lh_6.tif: No such file or directory
ERROR 4: ./scratch/lh_7.tif: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/gdal_merge.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_merge.py", line 428, in main
    ulx = file_infos[0].ulx
IndexError: list index out of range
ERROR 4: ./scratch/lw_0.tif: No such file or directory
ERROR 4: ./scratch/lw_1.tif: No such file or directory
ERROR 4: ./scratch/lw_2.tif: No such file or directory
ERROR 4: ./scratch/lw_3.tif: No such file or directory
ERROR 4: ./scratch/lw_4.tif: No such file or directory
ERROR 4: ./scratch/lw_5.tif: No such file or directory
ERROR 4: ./scratch/lw_6.tif: No such file or directory
ERROR 4: ./scratch/lw_7.tif: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/gdal_merge.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_merge.py", line 428, in main
    ulx = file_infos[0].ulx
IndexError: list index out of range
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
 ELMFIRE 2024.0831
 Reading &MISCELLANEOUS namelist group
 Reading &INPUTS namelist group
 Reading &OUTPUTS namelist group
 Reading &COMPUTATIONAL_DOMAIN namelist group
 Error: Problem with namelist group &COMPUTATIONAL_DOMAIN.
ERROR 4: ./outputs/*.bil: No such file or directory
ls: cannot access './outputs/time_of_arrival*.tif': No such file or directory
Usage: gdal_contour [-b <band>] [-a <attribute_name>] [-amin <attribute_name>] [-amax <attribute_name>]
                    [-3d] [-inodata] [-snodata n] [-f <formatname>] [-i <interval>]
                    [[-dsco NAME=VALUE] ...] [[-lco NAME=VALUE] ...]
                    [-off <offset>] [-fl <level> <level>...] [-e <exp_base>]
                    [-nln <outlayername>] [-q] [-p]
                    <src_filename> <dst_filename>

FAILURE: Missing destination filename.
```

I believe this error is due to the server refusing the connection. The server can be reached with pings:

```html
(venv) mrt@minerva elmfire/tutorials/03-real-fuels $ ping 172.92.17.198

PING 172.92.17.198 (172.92.17.198) 56(84) bytes of data.
64 bytes from 172.92.17.198: icmp_seq=1 ttl=41 time=179 ms
64 bytes from 172.92.17.198: icmp_seq=2 ttl=41 time=173 ms
```

However, when testing for the specific port:

```html
(venv) mrt@minerva elmfire/tutorials/03-real-fuels $ telnet 172.92.17.198 50052

Trying 172.92.17.198...
telnet: Unable to connect to remote host: Connection refused
```

It seems that either the port is closed or the service is not running.

Is anyone else experiencing problems with the Cloudfire server?

**Comment by lautenberger** [comment]
Hi Marcos,

Try cloning the latest ELMFIRE repository and trying again.  The worldgen server that provides the requisite geospatial inputs is now worldgen.cloudfire.io. There was some "off season" work underway back in December which is probably why the server wasn't available at that time. If you're still encountering problems create a new ticket.
